libamtrack/web

.travis.yml
Fixes #2 
Fixes #7 
refering to #7 i decided to also add ^feature, is should depoly when go commit to master or branch starts with feature, other branches won't trigger build, only start npm run build to check if build not fails.
I added feature branches to enable testing in web when someone do not have configured env.
=> travis native deploy and depoly only when to master or feature

docs/add_function.rst, docs/jsons.rst, package.json, src/functionsFromC/AT_D_RDD_Gy.js, src/functionsFromC/AT_beta_from_E.js, src/functionsFromC/AT_max_electron_range_m.js, src/functionsFromC/AT_max_electron_ranges_m.js, src/static/json/ElectronRange/MaxElectronRangeM.json, src/static/json/ElectronRange/MaxElectronRangesM.json, src/static/json/GlobalConfig.json, src/static/json/PhysicsRoutines/BetaFromE.json, src/static/json/RDD/RDD.json, src/static/json/dictionaries/ERModels.json, src/static/json/dictionaries/RDDModels.json
=> Max electron range

src/components/layouts/MainPage.js, src/static/json/GlobalConfig.json
=> - splited Physics category, removed fake functions

src/components/functions/FunctionsController.js, src/components/functions/forms/MoreOptionsForm.js, src/static/json/PhysicsRoutines/BetaFromE.json, src/static/json/PhysicsRoutines/EFromBeta.json, src/static/json/PhysicsRoutines/EFromGamma.json, src/static/json/PhysicsRoutines/EFromMomentum.json, src/static/json/PhysicsRoutines/EffectiveChargeFromBeta.json, src/static/json/PhysicsRoutines/EffectiveChargeFromE.json, src/static/json/PhysicsRoutines/GammaFromE.json, src/static/json/PhysicsRoutines/IncreaseEnergyStraggling.json, src/static/json/PhysicsRoutines/RelMomentumFromE.json, src/static/json/RDD/RDD.json, src/static/json/StoppingPower/MassStoppingPowerWithNo.json, src/static/json/StoppingPower/StoppingPowerWithNo.json
- Added default values for each axis
- Fixed bug with scale when changing plot type
=> Fixed problems with axis scale

docs/jsons.rst, src/components/functions/utils/SearchBox.js, src/components/layouts/FunctionsView.js, src/components/layouts/MainPage.js, src/components/layouts/SideMenu.js
- Added searchbox to menu
- Some decomposition
=> Searchbox in menu

src/components/functions/FunctionsController.js, src/components/functions/modals/ModalController.js, src/components/functions/utils/helpers.js
=> Improve download files

src/components/functions/FunctionsController.js, src/components/functions/forms/GenericForm.js, src/functionsFromC/AT_CSDA_energy_after_slab_E_MeV_u_multi.js, src/functionsFromC/AT_CSDA_energy_after_slab_E_MeV_u_single.js, src/functionsFromC/AT_CSDA_range_g_cm2_multi.js, src/functionsFromC/AT_CSDA_range_g_cm2_single.js, src/static/json/DataRange/CSDAEnergyAfterSlab.json, src/static/json/DataRange/CSDAEnergyAfterSlabMulti.json, src/static/json/DataRange/CSDAEnergyAfterSlabSingle.json, src/static/json/DataRange/CSDARangeMulti.json, src/static/json/DataRange/CSDARangeSingle.json, src/static/json/GlobalConfig.json
Added some method mentioned in #35:
- AT_CSDA_range_g_cm2_multi 
- AT_CSDA_range_g_cm2_single
- AT_CSDA_energy_after_slab_E_MeV_u_single 
- AT_CSDA_energy_after_slab_E_MeV_u_multi
Main columns order changed.
=> Added CSDA range/slab methods from #35

src/static/json/DataRange/CSDAEnergyAfterSlabSingle.json, src/static/json/PhysicsRoutines/EFromGammaSingle.json, src/static/json/PhysicsRoutines/EFromMomentumSingle.json, src/static/json/PhysicsRoutines/EffectiveChargeFromESingle.json, src/static/json/PhysicsRoutines/GammaFromESingle.json, src/static/json/PhysicsRoutines/RelMomentumFromESingle.json
=> better defauls for precision

package.json, src/components/functions/plots/PlotComponent.js
=> - fix plot labels

.gitignore, src/components/layouts/MainPage.js
=> Small changes in Main Page to display it on mobile

.travis.yml, src/components/layouts/MainPage.js, src/static/json/GlobalConfig.json
I added 3 new fields in GlobalConfig, the idea is to set them by travis during deploy using bash sed
=> Deploy info in footer

src/components/functions/plots/PlotComponent.js, src/static/json/DataRange/CSDAEnergyAfterSlabMulti.json
=> Added edit button and plot type to slab function

src/functionsFromC/AT_CSDA_energy_after_slab_E_MeV_u_multi.js, src/functionsFromC/AT_CSDA_energy_after_slab_E_MeV_u_single.js, src/static/json/DataRange/CSDAEnergyAfterSlabMulti.json, src/static/json/DataRange/CSDAEnergyAfterSlabSingle.json
=> unit conversion to user-friendly [cm]

src/functionsFromC/AT_max_electron_range_m.js, src/functionsFromC/AT_max_electron_ranges_m.js, src/static/json/ElectronRange/MaxElectronRangeMSingle.json, src/static/json/ElectronRange/MaxElectronRangesM.json, src/static/json/GlobalConfig.json, src/static/json/dictionaries/ERModels.json
=> Cleaning track width methods

docs/jsons.rst, src/components/functions/FunctionsController.js, src/components/functions/forms/GenericForm.js, src/components/functions/forms/MoreOptionsForm.js, src/components/functions/utils/helpers.js, src/static/json/DataRange/CSDAEnergyAfterSlabMulti.json, src/static/json/DataRange/CSDARangeMulti.json, src/static/json/ElectronRange/MaxElectronRangesM.json, src/static/json/PhysicsRoutines/BetaFromE.json, src/static/json/PhysicsRoutines/DoseFromFluence.json, src/static/json/PhysicsRoutines/EFromBeta.json, src/static/json/PhysicsRoutines/EFromGamma.json, src/static/json/PhysicsRoutines/EFromMomentum.json, src/static/json/PhysicsRoutines/EFromMomentumSingle.json, src/static/json/PhysicsRoutines/EffectiveChargeFromE.json, src/static/json/PhysicsRoutines/GammaFromE.json, src/static/json/PhysicsRoutines/IncreaseEnergyStraggling.json, src/static/json/PhysicsRoutines/RelMomentumFromE.json, src/static/json/RDD/RDD.json, src/static/json/StoppingPower/StoppingPowerWithNo.json
- move plotType to MoreOptions panel in all functions
- updated readthedocs (resolves #129)
- changed error message for single inputs (#111)
- fixed problem with 0 in logarithmic scale (resolves #112)
=> Move plotType to MoreOption and bugfixing

src/static/json/GlobalConfig.json, src/static/json/PhysicsRoutines/BetaFromE.json, src/static/json/PhysicsRoutines/DoseFromFluenceSingle.json, src/static/json/PhysicsRoutines/GammaFromE.json, src/static/json/PhysicsRoutines/RelMomentumFromE.json
minor fixes in JSON files
related to #35
=> lower energy range adjusted

src/components/functions/plots/PlotComponent.js
Resolve #166
Check changes on https://libamtrack.github.io/web_dev/ using mobile devie
=> Added dragmode=false to plot component

docs/jsons.rst, src/components/functions/forms/GenericForm.js, src/components/layouts/FunctionsView.js, src/components/layouts/MainPage.js, src/static/json/GlobalConfig.json, src/static/json/PhysicsRoutines/BetaFromE.json
=> Display validation error when start >= end and added footer.

src/components/functions/forms/GenericForm.js, src/index.html
Fixes recuring problem and moved inputs more rigth to let display bigger labels what probably will be use full to describe better paramters
=> Small fixes in validation entry module and let display bigger labels

src/functionsFromC/AT_dose_Bortfeld_Gy.js, src/static/json/GlobalConfig.json, src/static/json/PhysicsRoutines/BortfeldModelDepthDose.json
Still waiting for https://github.com/libamtrack/library/pull/52
=> initial Bortfeld model implementation

src/index.html
=> Google Analytics added

package.json, src/components/functions/FunctionsController.js, src/components/functions/modals/ModalController.js, src/components/layouts/MainPage.js
Link to bundle.js stats in footer
Fix view of calculations fixes #211
Expand data series by default fixes #210
=> Small fixes 

src/functionsFromC/AT_dose_Bortfeld_Gy.js, src/static/json/ProtonTherapyModels/BortfeldModelDepthDose.json
=> entrance dose instead of fluence

src/functionsFromC/AT_biological_dose_proton.js, src/static/json/GlobalConfig.json, src/static/json/ProtonTherapyModels/BiologicalDoseModels.json
=> biological dose models

docs/jsons.rst, src/components/functions/FunctionsController.js, src/static/json/PhysicsRoutines/DoseFromFluenceSingle.json
=> support for multiple items in calculator output

src/components/functions/forms/GenericForm.js
=> Added support for exponential notation, allowed negative values

src/static/json/PhysicsRoutines/DoseFromFluence.json, src/static/json/PhysicsRoutines/DoseFromFluenceSingle.json, src/static/json/RDD/RDD.json
=> better formatting of default units

src/components/functions/FunctionsController.js
=> Added updating 'start' field after changing X-scale to log

src/components/functions/FunctionsController.js, src/components/functions/utils/helpers.js, src/functionsFromC/AT_dose_Bortfeld_Gy.js, src/static/json/ProtonTherapyModels/BortfeldModelDepthDose.json
based on https://github.com/libamtrack/web/pull/278/commits
Fixes #344
=> calculator results added to some plots

src/static/json/PhysicsRoutines/EnergyLossDistributions.json
=> Proper energy units

src/components/layouts/MainPage.js, src/static/json/GlobalConfig.json
=> initial version of ack added

src/functionsFromC/AT_energy_spread_Bortfeld.js, src/static/json/GlobalConfig.json, src/static/json/ProtonTherapyModels/EnergyFromRangeSingle.json
=> proton beam parameters (energy + spread) calculated from range and FWHM

src/functionsFromC/AT_inactivation_cross_section_Katz_um2.js, src/static/json/GlobalConfig.json, src/static/json/TrackStructure/InactivationCrossSection.json, src/static/json/dictionaries/KatzRDDER.json
=> inactivation cross section UI

package.json
=> fix, downgrade antd to 3.26.12

src/static/json/Converters/BetaFromESingle.json, src/static/json/Converters/EFromBetaSingle.json, src/static/json/Converters/EFromGammaSingle.json, src/static/json/Converters/EFromMomentumSingle.json, src/static/json/Converters/GammaFromESingle.json, src/static/json/Converters/RelMomentumFromESingle.json, src/static/json/PhysicsRoutines/BetaFromE.json, src/static/json/PhysicsRoutines/EffectiveChargeFromE.json, src/static/json/PhysicsRoutines/EffectiveChargeFromESingle.json, src/static/json/StoppingPower/StoppingPowerWithNo.json
=> energy units fixed

.github/workflows/node.js.yml, README.md, docs/conf.py, docs/jsons.rst
=> new gh action deploy target

src/functionsFromC/AT_CSDA_range_g_cm2_multi.js, src/static/json/DataRange/CSDARangeMulti.json
=> calculate CSDA range for completely slowing down ions

docs/conf.py, docs/jsons.rst, src/static/json/GlobalConfig.json, src/static/json/dictionaries/ERModels.json, webpack.config.js
=> Add Kiefer ER model

src/functionsFromC/AT_CSDA_range_g_cm2_multi.js
Related to #1201 
This pull request refactors the `AT_CSDA_range_g_cm2_multi` function in `src/functionsFromC/AT_CSDA_range_g_cm2_multi.js` to improve maintainability, error handling, and code clarity. The changes include replacing outdated error handling with structured validation, enhancing memory management, and modernizing the function's structure.
* Replaced `alert`-based error handling with structured validation using `Error` objects, ensuring better error reporting and debugging. (`[src/functionsFromC/AT_CSDA_range_g_cm2_multi.jsR1-R101](diffhunk://#diff-c4a5c324dad7046ba9f031b01af2e40ff27a1a91a276a8dad6c0f786b03ac7e3R1-R101)`)
* Added detailed JSDoc comments to describe the function's purpose, parameters, and return values, improving code documentation. …
=> Refactor CSDA range
